/**
 * Regression tests generated by ChangeGuard AI (IBM Bob 2.0 agentic workflow).
 *
 * Change analysed: "10% discount on valid discount code" (discount-code change).
 * Defect identified: cancelOrder() does not restore product stock.
 *
 * When a confirmed order is later cancelled:
 *   - The payment is correctly refunded ✓  (existing test covers this)
 *   - The decremented stock is NOT restored ✗  (this file adds that coverage)
 *
 * Affected production file: src/modules/orders/orderService.js → cancelOrder()
 * Impact level: HIGH — inventory permanently lost on every customer cancellation.
 *
 * Gap 7 — stock NOT restored when a confirmed order is cancelled
 *   sub-scenario A: plain order (no discount code)
 *   sub-scenario B: discounted order cancelled after confirmation
 *   sub-scenario C: multi-item order cancelled, all stock lines restored
 *   sub-scenario D: cancelling a PENDING order (before payment succeeds)
 *                   — stock was decremented at placeOrder time and must still
 *                     be restored when the whole order record is cancelled later
 */

const { resetDb } = require('../../src/config/database');
const userService = require('../../src/modules/users/userService');
const productService = require('../../src/modules/products/productService');
const cartService = require('../../src/modules/cart/cartService');
const orderService = require('../../src/modules/orders/orderService');
const paymentService = require('../../src/modules/payments/paymentService');
const notificationService = require('../../src/modules/notifications/notificationService');

function resetAllCounters() {
  userService._resetIdCounter();
  productService._resetIdCounter();
  orderService._resetIdCounter();
  paymentService._resetIdCounter();
  notificationService._resetIdCounter();
}

// ─── shared setup ─────────────────────────────────────────────────────────────

let userId, productId;

beforeEach(() => {
  resetDb();
  resetAllCounters();

  const user = userService.createUser({ name: 'Alice', email: 'a@a.com', password: 'pw' });
  userId = user.id;

  const product = productService.createProduct({ name: 'Widget', price: 100, stock: 10 });
  productId = product.id;
});

// ─── Gap 7A ───────────────────────────────────────────────────────────────────
describe('Gap 7A — stock restored when a plain (no-discount) confirmed order is cancelled', () => {
  it('returns the decremented stock after cancelOrder', () => {
    cartService.addToCart(userId, productId, 3);

    // Stock: 10 → 7 after placeOrder
    const { order } = orderService.placeOrder({ userId });
    expect(productService.getProductById(productId).stock).toBe(7);
    expect(order.status).toBe('CONFIRMED');

    // After cancellation stock must return to 10
    orderService.cancelOrder(order.id);

    expect(productService.getProductById(productId).stock).toBe(10);
  });
});

// ─── Gap 7B ───────────────────────────────────────────────────────────────────
describe('Gap 7B — stock restored when a discounted confirmed order is cancelled', () => {
  it('returns the decremented stock after cancelOrder with discount code', () => {
    cartService.addToCart(userId, productId, 2);

    // Stock: 10 → 8 after placeOrder
    const { order } = orderService.placeOrder({
      userId,
      discountCode: 'SAVE10', // 10% off — total = 180, but stock effect is identical
    });
    expect(productService.getProductById(productId).stock).toBe(8);
    expect(order.total).toBe(180); // discounted amount: 200 * 0.9
    expect(order.status).toBe('CONFIRMED');

    // After cancellation stock must return to 10
    orderService.cancelOrder(order.id);

    expect(productService.getProductById(productId).stock).toBe(10);
  });

  it('the refund amount still equals the discounted total, not the original cart total', () => {
    cartService.addToCart(userId, productId, 1); // cartTotal = 100

    const { order } = orderService.placeOrder({ userId, discountCode: 'SAVE10' });
    expect(order.total).toBe(90); // 100 * 0.9

    orderService.cancelOrder(order.id);

    const payments = paymentService.getPaymentsByOrder(order.id);
    expect(payments[0].status).toBe('REFUNDED');
    expect(payments[0].amount).toBe(90); // refund = discounted charged amount
  });
});

// ─── Gap 7C ───────────────────────────────────────────────────────────────────
describe('Gap 7C — all stock lines restored when a multi-item order is cancelled', () => {
  it('restores stock for every product in the order', () => {
    const product2 = productService.createProduct({ name: 'Gadget', price: 50, stock: 20 });
    const product2Id = product2.id;

    cartService.addToCart(userId, productId, 4);  // stock 10 → 6
    cartService.addToCart(userId, product2Id, 5); // stock 20 → 15

    const { order } = orderService.placeOrder({ userId });
    expect(productService.getProductById(productId).stock).toBe(6);
    expect(productService.getProductById(product2Id).stock).toBe(15);

    orderService.cancelOrder(order.id);

    expect(productService.getProductById(productId).stock).toBe(10);
    expect(productService.getProductById(product2Id).stock).toBe(20);
  });
});

// ─── Gap 7D ───────────────────────────────────────────────────────────────────
// Note: placeOrder always transitions orders to CONFIRMED or CANCELLED before
// returning, so there is no PENDING order reachable via the public API.
// This sub-scenario documents that reality explicitly.
describe('Gap 7D — placeOrder always resolves to CONFIRMED or CANCELLED (no lingering PENDING)', () => {
  it('order status after placeOrder is never PENDING', () => {
    cartService.addToCart(userId, productId, 1);
    const { order } = orderService.placeOrder({ userId });
    expect(['CONFIRMED', 'CANCELLED']).toContain(order.status);
  });

  it('order status after failed-payment placeOrder is CANCELLED (not PENDING)', () => {
    cartService.addToCart(userId, productId, 1);
    const { order } = orderService.placeOrder({ userId, simulatePaymentFailure: true });
    expect(order.status).toBe('CANCELLED');
  });
});
